### ISSUE TITLE
DER_8 - missing cbsd_id update after second registration

### ISSUE THREAD

**Issue by redtechnologies** [Wireless-Innovation-Forum/Spectrum-Access-System#171]
It seems cbsd_id is not updated after step 4 (second registration).
As a result step 5 (heartbeat request) and step 6 (second deregistration) are performed using the wrong cbsd_id.

**Comment by janetliuboston** [comment]
Thank you for the comment. Will add the cbsd_id to this test case.
In practice, we hadn't added a different cbsd_id because it is a combination of FCC ID and CBSD serial number, and ends up being the same cbsd_id, but this is not specified in the TS, so it could be a different CBSD ID.

**Comment by janetliuboston** [comment]
For reference, about the CBSD ID, from WINNF-15-S-0112-V1 5 0 CBRS Operational and Functional Requirements, R2-SRR-08:
The CBSD ID shall have a one-to-one correspondence with the combination FCC ID + CBSD S/N and may be identical to that combination.

**Comment by janetliuboston** [comment]
Merged the fix in.
