### ISSUE TITLE
ContactInformation in "sas_impl_record_0.json" should be a array 

### ISSUE THREAD

**Issue by assaneRed** [Wireless-Innovation-Forum/Spectrum-Access-System#254]
comment on "sas_impl_record_0.json" object using by "WINNF_FT_S_SIR_testcase.py" in master branch
ContactInformation should be a array 
Refer to the last WINNF version for SAS-SAS protocol: V1.5.8 of 30 june 2017

**Comment by sushantparkhi** [comment]
Closing this as it has been fixed in PR https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/pull/255/files
