### ISSUE TITLE
Download Link in retrieve_fcc_files.py

### ISSUE THREAD

**Issue by jodumkeNTIA** [Wireless-Innovation-Forum/Spectrum-Access-System#381]
Issue:
&nbsp;&nbsp;A technical user has noticed a data download link currently appears missing.

Details:
&nbsp;&nbsp;-File "retrieve_fcc_files.py" Line 45
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;RetrieveURL('https://transition.fcc.gov/oet/info/maps/uscabdry/uscabdry.zip')
&nbsp;&nbsp;-File last updated 7-20-2015 (SVN Revision 6)
&nbsp;&nbsp;-Was unable to find an equivalent link using a search engine
&nbsp;&nbsp;-File is an FCC definition of the US and Canada border
&nbsp;&nbsp;-Below FCC page also has this broken link:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;https://www.fcc.gov/general/white-space-database-administration-q-page#US_border_def
&nbsp;&nbsp;-File is locally located at master/data/fcc/uscabdry.zip

Possible Fix:
&nbsp;&nbsp;Please consider if this link can be removed, used locally, or updated if the link can be easily found.

**Comment by sbdt-google** [comment]
You are right: the file does not exist anymore on that server.
I could not locate that file, so we will keep using the one downloaded and put in GitHub.
I removed the downlink link for now.

**Comment by jodumkeNTIA** [comment]
Thanks

**Comment by sbdt-google** [comment]
Hi John,

Shall I close the various tickets you creates and that should be addressed by the PR #565 ??
Or should let you verify and close them ?

Thanks,
Serge

**Comment by jodumkeNTIA** [comment]
Hi yes, you can close them as they might not be applicable anymore or now fixed.  Also, thanks for creating ticket #565.

**Comment by sbdt-google** [comment]
Ok will do. If any other related issue after #565 checked in, do not hesitate to create new issues.
