### ISSUE TITLE
Download Link in retrieve_itu_files.py

### ISSUE THREAD

**Issue by jodumkeNTIA** [Wireless-Innovation-Forum/Spectrum-Access-System#382]
Issue:
&nbsp;&nbsp;A technical user has noticed a data download link in retrieve_itu_files.py currently appears missing.

Details:
&nbsp;&nbsp;-File "retrieve_itu_files.py" Line 45
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;border = urllib2.urlopen(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'http://www.itu.int/dms_pubrec/itu-r/rec/p/R-REC-P.617-3-201309-I!!ZIP-E.zip')
&nbsp;&nbsp;-File last updated 1-24-2017 (SVN Revision 159)
&nbsp;&nbsp;-File appears missing using the below google search query:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;site:http://www.itu.int/ "R-REC-P" "zip" "climate zone"
&nbsp;&nbsp;-File appears to hold climate zone data
&nbsp;&nbsp;-File is located locally at master/data/itu/R-REC-P.617-3-201309-I!!ZIP-E.zip
&nbsp;&nbsp;-Other similar file download in script can still be downloaded:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R-REC-P.452-16-201507-I!!ZIP-E.zip

Possible Fix:
&nbsp;&nbsp;Please consider if this link can be removed, used locally, or updated if the link can be easily found.

**Comment by sbdt-google** [comment]
Thanks, problem fixed using the https version of the adress.
Please note on that one, that the location of the Tropoclim.txt file has a new updated document in december 2017. The accompanying zip file (v4) however does not hold the tropoclim.txt file anymore but the refractivity files found in Rec 452 normally. I think it is probably a mix up, and you should consider fixing this.

PR will be soon made with the changes, in combination of other geo data related fixes.

**Comment by jodumkeNTIA** [comment]
Thanks

**Comment by sbdt-google** [comment]
See #565
