### ISSUE TITLE
Download FTP in retrieve_ibfs.py

### ISSUE THREAD

**Issue by jodumkeNTIA** [Wireless-Innovation-Forum/Spectrum-Access-System#383]
Issue:
&nbsp;&nbsp;A technical user has found a possible system specific ftp error in a data download.

Details:
&nbsp;&nbsp;-File "retrieve_ibfs.py" Line 32:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fcc.download_if_newer('pub/Bureaus/International/databases/ibfs.txt', 'ibfs.txt')
&nbsp;&nbsp;-File last updated 12-1-2015 (SVN Revision 40)
&nbsp;&nbsp;-Can be fixed by updating Lines 25-32 with:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fccZip = ftputil.FTPHost('ftp.fcc.gov', 'anonymous', '')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fccTxt = ftputil.FTPHost('ftp.fcc.gov', 'anonymous', '')

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print 'Downloading IBFS.zip database file'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fccZip.download_if_newer('pub/Bureaus/International/databases/IBFS.zip', 'IBFS.zip')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fccZip.quit()

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print 'Downloading ibfs.txt schema'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fccTxt.download_if_newer('pub/Bureaus/International/databases/ibfs.txt', 'ibfs.txt')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fccTxt.quit()
&nbsp;&nbsp;-Error attached to this issue
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[IBFSError(1-16-17).txt](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/files/1636313/IBFSError.1-16-17.txt)
&nbsp;&nbsp;-Error similar to:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;https://stackoverflow.com/questions/38867346/nonetype-object-has-no-attribute-sendall-python
&nbsp;&nbsp;-Error occured on python x86 2.7.12 ftputil 3.3.1

Possible Fix:
&nbsp;&nbsp;Please consider updating the code.  Presently, it likely could only be a system or software version specific error.

**Comment by sbdt-google** [comment]
Thanks, problem fixed according to your proposal.
PR will be soon made, in combination of other geo data related fixes.

**Comment by jodumkeNTIA** [comment]
Thanks

**Comment by sbdt-google** [comment]
Fixed in #565
