### ISSUE TITLE
Download Link in retrieve_orig_ned.py

### ISSUE THREAD

**Issue by jodumkeNTIA** [Wireless-Innovation-Forum/Spectrum-Access-System#385]
Issue:
&nbsp;&nbsp;A technical user has found the NLCD download appears to require an ssl context on the below stated computer.

Details:
&nbsp;&nbsp;-File "retrieve_orig_nlcd.py" Line 36:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;f = urllib2.urlopen(resource)
&nbsp;&nbsp;-File last updated 1-8-2018 (SVN Revision 2187)
&nbsp;&nbsp;-Can fix by replacing Line 36 with:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context = ssl._create_unverified_context()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;f = urllib2.urlopen(resource, context=context)
&nbsp;&nbsp;-Was run on windows python x86 2.7.12 urllib2 2.7
&nbsp;&nbsp;-Error is below:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[NLCDError(1-16-17).txt](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/files/1636704/NLCDError.1-16-17.txt)

Possible Fix:
&nbsp;&nbsp;Please consider applying the above fix or a different fix.

**Comment by sbdt-google** [comment]
Thanks, problem fixed according to your proposal.
PR will be soon made, in combination of other geo data related fixes.

**Comment by jodumkeNTIA** [comment]
Thanks

**Comment by sbdt-google** [comment]
Fixed in #565
