### ISSUE TITLE
Indentation in retrieve_uls_files.py

### ISSUE THREAD

**Issue by jodumkeNTIA** [Wireless-Innovation-Forum/Spectrum-Access-System#386]
Issue:
&nbsp;&nbsp;A technical user has found the ULS download appears to have indentation that creates a local error and is slightly incorrect.

Details:
&nbsp;&nbsp;-File "retrieve_uls_files.py" Line 69:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;schema.close()
&nbsp;&nbsp;-File last updated 3-16-2016 (SVN Revision 41)
&nbsp;&nbsp;-Can fix by only indententing line 69 with two spaces instead of three spaces.
&nbsp;&nbsp;-Was run on windows python x86 2.7.12
&nbsp;&nbsp;-Error is below:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[ULSError(1-16-18).txt](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/files/1636762/ULSError.1-16-18.txt)

Possible Fix:
&nbsp;&nbsp;Please consider applying the above fix or a different fix.

**Comment by sbdt-google** [comment]
Thanks, problem fixed according to your proposal.
PR will be soon made, in combination of other geo data related fixes.

**Comment by jodumkeNTIA** [comment]
Thanks

**Comment by sbdt-google** [comment]
Fixed in #565
