### ISSUE TITLE
SSS test cases do not inject peer SAS

### ISSUE THREAD

**Issue by kate-harrison** [Wireless-Innovation-Forum/Spectrum-Access-System#431]
#426 was merged before this agreed-upon change could be made. This issue will track the progress of the fix.

**Comment by jni2000** [comment]
working in progress, will do asap.

**Comment by jni2000** [comment]
please ignore the first fix item "fix for SSS test cases do not inject peer SAS #431", there are some errors in it.
The second one "fix for SSS test cases do not inject peer SAS #431 #436" is correct.

**Comment by kate-harrison** [comment]
This has been fixed.
