### ISSUE TITLE
Refactor assertTlsHandshakeSucceed/assertTlsHandshakeFailure

### ISSUE THREAD

**Issue by pmarks-net** [Wireless-Innovation-Forum/Spectrum-Access-System#488]
This was found during https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/pull/439, and I want to write it down for tracking purposes:

https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/security_testcase.py defines the following pair of functions:

- `assertTlsHandshakeSucceed()`
- `assertTlsHandshakeFailure()`

But they are implemented as two independent functions, so it's non-trivial to prove whether success and failure are mutually exclusive states.

Instead, they should share a common function that answers "did the TLS handshake succeed?"

**Comment by jni2000** [comment]
Thanks, Paul. We will take a look of it.

**Comment by pmarks-net** [comment]
`assertTlsHandshakeFailure()` is also problematic because it doesn't care *why* the failure occurred:

> https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/pull/467#issuecomment-378360321
> The SCS.11 and SDS.11 passed because they expect TLS handshake failure and the TLS handshake fails although for a different reason (‘unknown ca’ instead of ‘certificate revoked’)."
