### ISSUE TITLE
DP test harness needs to use DP certs

### ISSUE THREAD

**Issue by kate-harrison** [Wireless-Innovation-Forum/Spectrum-Access-System#517]
They are currently using CBSD-type certificates.

**Comment by kate-harrison** [comment]
I think we just need to change the default client cert used in request_handler.py (either point to a DP-type cert, or alter the cert with that filename to be DP-type).

PR #447 adds the TEST extension to the certs, which may or may not be sufficient. Let's use DP-type certs just to be safe.

**Comment by norbertbarbosa** [comment]
done in PR #521
