### ISSUE TITLE
Small problems with SCS/SDS/SSS.17-19

### ISSUE THREAD

**Issue by kate-harrison** [Wireless-Innovation-Forum/Spectrum-Access-System#519]
Hi James and all,

 

Here are follow up comments I sent out before.

 

[1]Some testcases doesn’t call the SasReset() before injections/registrations, reset is needed.

 

    Comment:

    All the testcases need to reset SAS UUT to the baseline state. This is required in the test spec.

  However, many of SxS don’t send admin/reset to the SAS UUT.

      Please add self.SasReset() for each testcase.

 

        For example, some testcases call assertRegistered() or assertRegisteredAndGranted() without admin/reset. They don’t have admin/reset. Only doCbsdTestCipher have admin/reset which is used in SxS.1~5.

 

[2]The code calls generate_short_lived_certs.sh but it gives error

 

security_testcase.py line277

276    # Build short lived certificate command

277    command = "cd {0} && ./generate_short_lived_certs.sh {1} {2} {3}".format(cert_path, client_type,

278                                                                             cert_name, str(cert_duration_minutes))

279    # Create the short lived certificate

280    command_exit_status = subprocess.call(command, shell=True)

 

  (1)I think command needs to include ‘bash’

 

      Comment:

line 280:  command_exit_status = subprocess.call(command, shell=True)

         this doesn’t run.

 

         If I give ‘bash’ like below, it runs.

         command = "cd {0} && bash ./generate_short_lived_certs.sh {1} {2}…

command_exit_status = subprocess.call(command, shell=True)

 

         I suggest to add ‘bash’ like above.

 

   (2)file generate_short_lived_certs.sh includes ‘\r’.

 

      Comment:

“generate_short_lived_certs.sh” runs itself, but when called from subprocess(), it gives error.

       If I remove ‘\r’ in the file, it runs.

 

       simple_crl_server.py is the same situation when it calls revoke_and_geerate_crl.sh.

       I suggest to remove ‘\r’ from the .sh files.

 

 

Best Regards,

Takashi

**Comment by jni2000** [comment]
Thanks, Kate, we will address this.

**Comment by kate-harrison** [comment]
Has this issue been resolved or is there more work that needs to be done?

**Comment by jni2000** [comment]
we will take care of this.

**Comment by jni2000** [comment]
issue has been addressed and fixed in PR #573
