### ISSUE TITLE
Clean up /data/ntia/protection_zones.kml

### ISSUE THREAD

**Issue by kate-harrison** [Wireless-Innovation-Forum/Spectrum-Access-System#526]
Remove ground-based EZs from this file so that it only includes coastal EZs (for use in Cat A DPA neighborhood determination).

**Comment by sbdt-google** [comment]
Will fix the reference database as it affects the zones.py reader ref model, used for those.

**Comment by kate-harrison** [comment]
I think this is now fixed?

**Comment by sbdt-google** [comment]
Not yet, although it might be obsolete now (most likely deprecated although not yet acted on the spec side).

**Comment by sbdt-google** [comment]
This file no more used as part of the latest spec update.
