### ISSUE TITLE
Clean up /data

### ISSUE THREAD

**Issue by kate-harrison** [Wireless-Innovation-Forum/Spectrum-Access-System#527]
Remove obsolete files, update outdated files.

Can remove ibfs/ completely, we will use the new FCC API for FSS. Can remove uls/ completely, we don't need to mirror old FCC data.

Hope to eventually delete census/ (maybe move it to SAS-Data repo instead?).

**Comment by sbdt-google** [comment]
Made cleanup in #542.

**Comment by sbdt-google** [comment]
Submitted first set of cleanup: some things have been removed, and some have been put in legacy folder (both data and related scripts)

Final cleanup will be finalized later.

**Comment by sbdt-google** [comment]
Other cleanup as part of #565

**Comment by sbdt-google** [comment]
Final cleanup will be done after census script integration:
  - possible removal of the census_legacy folder and scripts
