### ISSUE TITLE
EXZ1 conditionals are preloaded before whitelisting

### ISSUE THREAD

**Issue by jcereced** [Wireless-Innovation-Forum/Spectrum-Access-System#598]
on lines 231-233 we are preloading conditionals before whitelisting

 # Pre-load conditional registration data for N2,N3 and N4 CBSDs.
    if ('conditionalRegistrationData' in config) and (config['conditionalRegistrationData']):
      self._sas_admin.PreloadRegistrationData(config['conditionalRegistrationData'])

**Comment by harinineelu** [comment]
Fixed - https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/pull/603

**Comment by kate-harrison** [comment]
As far as I know, this has been fixed so I will close this issue. Please re-open and let us know what work remains, if needed.
