### ISSUE TITLE
WDB.1 issue injecting database URL

### ISSUE THREAD

**Issue by jcereced** [Wireless-Innovation-Forum/Spectrum-Access-System#622]
When the TH is injecting the database URL onto the SUUT it's not using the proper format:

ln 162-164

# Inject the PAL database URL into the SAS UUT.
    self._sas_admin.InjectDatabaseUrl(pal_database.getBaseUrl()+
                                      config['palDatabaseConfig']['fileUrl'])

it's sending

/admin/injectdata/database_url :
https://localhost:8003/rest/pal/v1/

it should send 

{ "PAL" : "https://10.250.12.169:8003/rest/pal/v1/nameofdbfile.json"}

**Comment by jni2000** [comment]
fixed in PR #624
