### ISSUE TITLE
WDB.2 issues

### ISSUE THREAD

**Issue by jcereced** [Wireless-Innovation-Forum/Spectrum-Access-System#623]
a couple of issues on WDB.2

 Line 291

csv_writer   =   csv.writer(output_file, delimimter=',')
--

i'm guessing it needs to be delimiter

I’m assuming that needs to be delimiter…

After I change that I’m having a problem when the TH is trying to injects the database url.  Below is what it’s sending:

[INFO] 2018-05-10 10:13:05,477 request_handler.py:126 POST Request to URL 

/admin/injectdata/database_url :
"testcases/testdata/cpi_db/index.csv"

It should be sending something like this:

{ “CPI”  :  "http://localhost:xxxx/path/index.csv"}

**Comment by jni2000** [comment]
The fix is done in PR #624 
https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/pull/624
