### ISSUE TITLE
Error in calling getRandomLatLongInPolygon(...) in GPR test cases

### ISSUE THREAD

**Issue by jni2000** [Wireless-Innovation-Forum/Spectrum-Access-System#632]
Takashi reported this issue as described below

https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/93adfd017e70bdeddf8408a76001b4855231df33/src/harness/testcases/WINNF_FT_S_GPR_testcase.py

[1]  getRandomLatLongInPolygon()  in line 192  in generate_GPR_2_default_config 

   Current: (e.g. Line 192) 
    device_3['installationParam']['longitude'] = getRandomLatLongInPolygon(gwpz_record_1['zone'])

I think the type mismatches. 

Expected: I’m not sure but [‘zone’] is not needed here?
device_3['installationParam']['longitude'] = getRandomLatLongInPolygon(gwpz_record_1)

**Comment by kate-harrison** [comment]
I'm closing this, as I believe this issue is now fixed.
