### ISSUE TITLE
Per-SAS headroom not added to IAP results

### ISSUE THREAD

**Issue by kate-harrison** [Wireless-Innovation-Forum/Spectrum-Access-System#637]
As noted by Navin from CommScope:
> When computing the allowed reference aggregate in calculatePostIapAggregateInterference(), the head-room margin per SAS is not accounted for in the calculation

From my reply:
> I agree, it seems that the headroom is not being added back in. The [current equation in line 643](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/d14fe83afb23f5187b2e3ad65ec9bde8f2a91f12/src/harness/reference_models/iap/iap.py#L643) adds the leftover and the aggregate interference caused by CBSDs managed by SAS UUT, but it omits the difference between `q_p` and the original threshold (i.e. the headroom). I guess we need to add another arg to `calculatePostIapAggregateInterference()` to denote the original threshold, and then this value can be used on line 643.

**Comment by jni2000** [comment]
Kate, Navin et. al.

We revisited the IAP implementation and believe that the per SAS Headroom was added to the IAP result. No code change is required. Below is the explanation for the same:

calculatePostIapAggregateInterference() is implemented as below:

Ap_IAP_Ref = [cid:image004.png@01D3EB61.AA52E230]

Input to calculatePostIapAggregateInterference() is passed as q_p – mg_p.

For example :
performIapForEsc() calculates  q_p – mg_p value as below

# Actual protection threshold used for IAP - calculated by applying
# a pre-defined Pre-IAP headroom (Mg) at each protection threshold(Q)
  esc_iap_threshold = interf.dbToLinear(esc_thresh_q - MARGIN_ESC_DB)   (line 299 )


Above parameter is passed to calculatePostIapAggregateInterference() API  as below

ap_iap_ref = calculatePostIapAggregateInterference(esc_iap_threshold, num_sas,
                 asas_interference, aggregate_interference)  -- (Line 337)


James Ni
Director of SAS System
www.federatedwireless.com<http://www.federatedwireless.com/>
https://www.linkedin.com/pub/james-ni/4/3b9/24a
978.996.7480
[Description: Macintosh HD:Users:Sam:Dropbox (Bluetext):Federated Wireless:Creative:Logo:Logo Lock Up:Final-Lockup:Federated Wireless No Tag:FedWireless-lockup-notag-web.png]
