### ISSUE TITLE
SIQ.3 checks on C2 and C4 are not correct

### ISSUE THREAD

**Issue by jni2000** [Wireless-Innovation-Forum/Spectrum-Access-System#639]
In SIQ.3, 

1. CBSD C2 is out of the range of every protected entity and thus the queried frequency range of 3550-3700 shall be all available. The current checks failed when respond with 3550-3700.
2. CBSD C4 is only within the 150km range of the FSS and thus the frequency range of 3550-3650 shall be all available and returned in response. The current checks for C4 failed when responded with 3550-3650.

**Comment by kate-harrison** [comment]
I agree, this appears to be a bug in the code. The [check](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/testcases/WINNF_FT_S_SIQ_testcase.py#L241) uses the function `assertChannelsContainFrequencyRange()`, which based on [this test](https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/testcases/helper_unit_testcase.py#L54) will fail the assertion if the list of channels is *larger* than the frequency range that's supposed to be covered. I suggest we create a copy of this function which removes that constraint and use it for C2 and C4 in SIQ.3.

**Comment by jni2000** [comment]
Ok, will fix this. Thanks.

**Comment by kate-harrison** [comment]
This is fixed in #649; closing.
