### ISSUE TITLE
"pal_db" and "cpi_db" are missing for WDB.1 and WDB.2

### ISSUE THREAD

**Issue by jni2000** [Wireless-Innovation-Forum/Spectrum-Access-System#640]
"pal_db" and "cpi_db" folders as well as contained database data are missing in master branch. They are required for WDB.1 and WDB.2. Please take a look.

**Comment by kate-harrison** [comment]
They are intentionally omitted since they are auto-generated when you generate the default config and run the test case. There is no need to store anything else. Please close if you agree.
