### ISSUE TITLE
FSS Mask Loss calculation is not correct

### ISSUE THREAD

**Issue by jni2000** [Wireless-Innovation-Forum/Spectrum-Access-System#652]
> Navin
the getFssMaskLoss() in interference.py  needs to be corrected. The current implementation does not look right.

> Kate
(For reference and easy access later, here is the function in question.) We're seeing some issues in this function as well. If you can create the PR, we will happily review it. 

>jni2000
We also reviewed the the getFssMaskLoss() in interference.py and agreed that there is an issue. We are fixing it right now will deliver a fix soon after the headroom fix.

**Comment by kate-harrison** [comment]
James, do you have a fix for this ready to review? We don't have much time left.

**Comment by kate-harrison** [comment]
Fixed, closing.
