### ISSUE TITLE
Zone to be injected in PCR7 does not have valid format

### ISSUE THREAD

**Issue by jcereced** [Wireless-Innovation-Forum/Spectrum-Access-System#680]
In PCR7 a zone is injected into the SUUT

 

 

/admin/injectdata/zone :

{"record": {"terminated": false, "name": "PPA Zone 0", "zone": {"type": "Polygon", "coordinates": [[[-100.61355286470628, 39.06028870255636], [-100.6103309414228, 39.05904150644663], [-100.60427196105131, 39.056756972863944], [-100.60425345765879, 39.05674997526318], [

 

 

 

This is not consistent with the zones we inject in other TCs:

 

 

 

/admin/injectdata/zone :

{"record": {"terminated": false, "name": "PPA Zone 0", "zone": {"type": "FeatureCollection", "features": [{"geometry": {"type": "Polygon", "coordinates": [[[-97.23861694335938, 38.865374851611634], [-97.31964111328125, 38.7615795117574], [-97.16995239257811, 38.739088441876866], [-97.16171264648436, 38.86751337001198], [-97.2386

 

 

It looks like the zone record in the PCR 7 config was not created properly

 

 

The second one is the correct one and what the PCR7 config should look like when it’s fixed

**Comment by kate-harrison** [comment]
I think this has been fixed in #684 so I will close the issue.
