### ISSUE TITLE
ESC Record Antenna pattern values not as per spec

### ISSUE THREAD

**Issue by nasrinivasa** [Wireless-Innovation-Forum/Spectrum-Access-System#685]
https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/ed8642f2154d192300afda39c8c5f76cf13f6c37/src/harness/reference_models/iap/test_data/esc_0.json#L10

The antenna gain values should be referenced with respect to the bore-site but the current record is not doing so. This needs to be addressed.

**Comment by kate-harrison** [comment]
I guess your point is that the high-gain points should centered around 0 degrees rather than around ~180 degrees?

James, can your team take a look at this? I think they were the original authors of this code.

**Comment by jni2000** [comment]
ok, we will take a look of this one.

**Comment by kate-harrison** [comment]
This was fixed in #696 so I'm closing the issue now.
