### ISSUE TITLE
Improve MCP.1 parallelisation 

### ISSUE THREAD

**Issue by TaranFurnell** [Wireless-Innovation-Forum/Spectrum-Access-System#689]
Currently MCP.1 executes entirely in a single thread (excluding reference models). While this is functional there are several places where the test harness will be executing a computationally intensive reference model only to then trigger a computationally intensive calculation on the SAS UUT side such as CPAS (or vice versa). As MCP.1 is expected to take a considerable amount of time to execute adding some multi-threading of disjoint components is expected to be reasonably useful in reducing the runtime.

**Comment by kate-harrison** [comment]
Fixed in #690 which will be submitted soon.
