### ISSUE TITLE
Bug in FSS neighboring GWBL code

### ISSUE THREAD

**Issue by piotrfilipiuk** [Wireless-Innovation-Forum/Spectrum-Access-System#691]
I think there is an issue with the following function:

def getFssNeighboringGwbl(gwbl_records, fss_records)

defined in 

src/harness/reference_models/pre_iap_filtering/pre_iap_util.py

My understanding of the requirement is that:

If a grant's frequency range overlaps with [3650, 3700] AND the CBSD that the grant belongs to is within 150 km from an FSS station AND the FSS station has GWBL within 150 km, then we must terminate the grant, and exclude it from CPAS.

The bug is in the following lines:

fss_high_freq = fss_params['operationParam']['operationFrequencyRange']['highFrequency']
    if fss_high_freq >= 3700e6:
      continue

I believe what we should be checking is lowFrequency i.e. if the lowFrequency >= 3700e6 we should exclude that fss_record from the result, since there is no CO_CHANNEL protection needed.

**Comment by jni2000** [comment]
reviewed and approved.
