### ISSUE TITLE
WG4 change to SIQ.3: SIQ response for C1 is slightly changed

### ISSUE THREAD

**Issue by kate-harrison** [Wireless-Innovation-Forum/Spectrum-Access-System#693]
Instead of 
> upper edge of F to 3650 MHz

we now have

> upper edge of F to 3700 MHz

for C1 in SIQ.3. This should just be a matter of changing this line

>     self.assertChannelsOverlapFrequencyRange(channels_high[0], freq_range_high, constrain_low=True, constrain_high=False)

to

>     self.assertChannelsOverlapFrequencyRange(channels_high[0], freq_range_high_all, constrain_low=True, constrain_high=True)

and creating `freq_range_high_all` which spans `pal_high_frequency` to 3700 MHz.

**Comment by harinineelu** [comment]
Fixed.
