### ISSUE TITLE
FSS: wrong interference and channelization if FSS band not in multiple of 5Mhz

### ISSUE THREAD

**Issue by sbdt-google** [Wireless-Innovation-Forum/Spectrum-Access-System#698]
The FSS co-channel do not align properly the channels to 5MHz boundary, so if the frequency are not in multiple of 5MHz:
  - the channelization will not be aligned on multiple of 5MHz. 
 - IAP versus Agg interference are doing same thing so coherent. 
 - however the interference does not take into account the overlap of the grant and passband of the FSS, and basically consider the full EIRP in the 5MHz band and not the actual overlapped band

FSS Blocking is ok however, because channelization is done starting at 3550, so aligned with the grants channels (provided the getFssMaskLoss() is done properly (see current PR #667)

**Comment by kate-harrison** [comment]
Fixed in #716 which will be submitted soon.
