### ISSUE TITLE
Inefficient repeated interference calculation for same entities

### ISSUE THREAD

**Issue by sbdt-google** [Wireless-Innovation-Forum/Spectrum-Access-System#699]
In both IAP loop and aggregate interference, there is a loop on the 5MHz channels.
In IAP there is also a convergence loop.

For both type of loop, the code calls "computeInterference", often with same parameters (or only the channel which change). The computeInterference is the heavy duty code calling the propagation model and antenna gains.
So because a grant spans several channel, the calculation is basically repeated several times with same parameters.

The speed can be greatly improved by using the `cache.LruCache()` decorator, at least on the popagation model. Doing it directly on the interference will not work everywhere as the channel will change between calls (but often with no effect on the calculated interference) - it is possible however in the IAP loop.

**Comment by kate-harrison** [comment]
Is this change critical or just "nice to have"?

**Comment by sbdt-google** [comment]
Depends, "nice to have" as it is not mandatory. But will speed up typically the MCP by a factor of 2x to 8x,
which is nice to have when trying to troubleshoot a failing test. And it is easy to integrate in the code, so will have a quick shot at this, once "bugs" are fixed.

**Comment by sbdt-google** [comment]
Fixed in #732. The memoizing avoid some of the repetitive calls to the hybrid model (and only this one), 
as it is the most consuming (GWPZ/PPA). Other parts of the computeInterference, such as antenna have not been memoized.
