### ISSUE TITLE
IPR.2 default config is not valid

### ISSUE THREAD

**Issue by TaranFurnell** [Wireless-Innovation-Forum/Spectrum-Access-System#704]
The current IPR.2 config was a placeholder and is does not conform to the requirements of the test, that being the second set of grants must exceed the allowed threshold if the DPA were activated.

**Comment by kate-harrison** [comment]
James, could you please ask your team to work on this? I think you can quickly reach the goal by using CBSDs that are extremely close to the DPAs.

**Comment by jni2000** [comment]
ok, will work on this.

**Comment by kate-harrison** [comment]
Fixed in #714 which will be submitted soon.
