### ISSUE TITLE
signal.alarm not cleaned up on test error

### ISSUE THREAD

**Issue by TaranFurnell** [Wireless-Innovation-Forum/Spectrum-Access-System#705]
Code using signal.alarm does not clean up the alarm on test failure. This can affect other tests if run in the same execution. Recommended approach: Change all signal alarms to do all time-based checks the same as in PR #690

**Comment by kate-harrison** [comment]
James, are you able to address this? I think it should be fairly straightforward given that Taran has provided an example in #690.

**Comment by jni2000** [comment]
ok, will work on this

**Comment by kate-harrison** [comment]
Fixed in #715 which will be submitted soon.
