### ISSUE TITLE
GPR_2 etc errors

### ISSUE THREAD

**Issue by jni2000** [Wireless-Innovation-Forum/Spectrum-Access-System#721]
Takashi wrote:

[1] zone_purge.py  ['record'] is missing. 
https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/reference_models/pre_iap_filtering/zone_purge.py

      # Purge the overlapping grants
      pre_iap_util.purgeOverlappingGrants(cbsds_within_gwpz,
                                          #gwpz_record['deploymentParam'][0]
                                          gwpz_record['record']['deploymentParam'][0]
                                          ['operationParam']['operationFrequencyRange'])

[2] Exception in thread Thread-7:
https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/master/src/harness/testcases/WINNF_FT_S_MCP_testcase.py

WINNF_FT_S_MCP_testcase.py", line 61    self.testcase.performAggregateInterferenceCheck()
    performAggregateInterferenceCheck
    ppa_ap_iap_ref_values = self.ppa_ap_iap_ref_values_list[index]
    IndexError: list index out of range

**Comment by jni2000** [comment]
I see the problem of [1] in Takashi's finding. Will put a fix in. 
For [2], I do not quite understand the issue yet. Can someone help on this ?

**Comment by jni2000** [comment]
The [1] issue as Takashi pointed out had been fixed in PR #722.

**Comment by kate-harrison** [comment]
[2] is fixed in #727.
