### ISSUE TITLE
Bug in checkForOverlappingGrants() in pre_iap_util.py

### ISSUE THREAD

**Issue by piotrfilipiuk** [Wireless-Innovation-Forum/Spectrum-Access-System#724]
The check for grant's frequency overlap in:

def checkForOverlappingGrants(grant, frequency_range)

is incorrect. It does not correctly handle the case where grant's frequency range is completely contained in the |frequency_range|.

For example:

Grants frequency range: [3680, 3690]
Protected frequency range: [3650, 3700]

**Comment by kate-harrison** [comment]
Fixed in #725.
