### ISSUE TITLE
IAP Aggregate Comparision for a single SAS case is not right

### ISSUE THREAD

**Issue by nasrinivasa** [Wireless-Innovation-Forum/Spectrum-Access-System#761]
https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/85bc0e02327a151646699d7f50e5806555608b00/src/harness/testcases/WINNF_FT_S_MCP_testcase.py#L612

When comparing the aggregate interference against the absolute threshold, for a single SAS case, the absolute value of the threshold is not adjusted for the IAP reference BW. The aggregate interference calculated is for the IAP reference BW and hence the threshold used for comparision should also be adjusted for the IAP reference BW. 

I have just highlighted the PPA case but, this has to be done for all protection point type.

I

**Comment by nasrinivasa** [comment]
Kate,
   Yes you are right, just need to change the constants that are being used. Sure, we can prepare a PR for this.

Navin

**Comment by kate-harrison** [comment]
FYI this was fixed in #762; closing.
