### ISSUE TITLE
WINNF_FT_S_PAT_testcase.py antenna gain comparison issue

### ISSUE THREAD

**Issue by candersonNTIA** [Wireless-Innovation-Forum/Spectrum-Access-System#768]
In WINNF-TS-0061, Section 8.2.4.1 (PAT.1 Test), the test harness is required to implement the following check:

**> The FSS antenna gain calculated by the SAS UUT shall be no less than the FSS antenna gain calculated by the reference implementation minus 0.2 dB.**

This language can be expressed by the following equation:

     G_{SAS} >= G_{Ref} - 0.2 dB

where G_{SAS} is the antenna gain calculated by the SAS and G_{Ref} is the gain calculated by the reference model.  Thus, the SAS is allowed to _over_-estimate the FSS antenna gain, providing a conservative estimate of aggregate interference into the FSS as the victim receiver.

However, the code implemented is:

     `(sas_response['rxAntennaGainDbi'] < (ref_response['rxAntennaGainDbi'] + .2)))`

Mathematically:

     G_{SAS} < G_{Ref} + 0.2 dB

Although the two statements are mathematically equivalent, they result in different behaviors by the test harness.  In the latter case, the SAS is allowed to _under_-estimate the FSS gain, which would result in an excess of interference allowed into the FSS.  This behavior was confirmed by running several scenarios against a provided SAS implementation.  Additionally, the code as implemented does not track the words of WINNF-TS-0061, Section 8.2.4.1 PAT.1 check.

We believe the same issue exists with the CBSD antenna gain test, but did not specifically evaluate that part of the test harness code.

**Comment by kate-harrison** [comment]
Thanks for the report! This (and a similar issue which affected the CBSD antenna gain check) has been fixed in #769.
