### ISSUE TITLE
Possible Missing Census Data for PCR Tests

### ISSUE THREAD

**Issue by jodumkeNTIA** [Wireless-Innovation-Forum/Spectrum-Access-System#794]
Issue:
&nbsp;&nbsp;&nbsp;A technical user may have found missing census data in the main repository for the PCR tests.

Details:
&nbsp;&nbsp;&nbsp;-PCR tests state "20063955100.json" is missing.
&nbsp;&nbsp;&nbsp;-PCR tests state "20063955200.json" is present.
&nbsp;&nbsp;&nbsp;-The below links have conflicting values for "20063955200.json":
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/tree/master/data/census_tracts/20063955200.json
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;https://github.com/Wireless-Innovation-Forum/SAS-Data/blob/master/census/census2.zip
&nbsp;&nbsp;&nbsp;-Testing issue when using "20063955100.json" from the SAS-Data repo.

Issue:
&nbsp;&nbsp;&nbsp;Please consider adding the "20063955100.json" missing file, replacing both json files, or possibly changing the test case values if needed.  Also, please re-run the PCR tests if any changes need to be made.

**Comment by sbdt-google** [comment]
Not sure to understand the issue. 
The data/census_tracts/ directory is just a placeholder for the census tracts found in SAS Data either by:
 - copying them from SAS-Data/census (after unzip) to that directory
 - or making a soft link from data/census-tracts to SAS-Data/census
 - or changing the geo/CONFIG.py variables

The fact that one single JSON file has been included there is just for unit test to be able to run, I think (unit test should not depend on manual process as described earlier).

Running full harness test however requires that full manual config to be done properly. So it seems to me that that config may not have been done correctly by the technical user.

**Comment by jodumkeNTIA** [comment]
Was already data in there and assumed it was the test data.  Will copy both json files from SAS-Data/census and retest now.

**Comment by jodumkeNTIA** [comment]
Ok thanks, your second point was the error we were having.  It looks like somebody(could have been me) created the link/mount in a nested folder to possibly keep the json file that was there(20063955200.json).  Tests seem to be working and passing now, and will fully run PCR when servers are available.
