### ISSUE TITLE
security_testcase.py:assertTlsHandshakeFailureOrHttp403: for sas-sas, tls handshake verification should be checked with sas-sas-rsa-url rather than admin url

### ISSUE THREAD

**Issue by chandanahs** [Wireless-Innovation-Forum/Spectrum-Access-System#803]
When AdminApiBaseUrl and SasSasRsaBaseUrl in sas.cfg is different, TLS verification for sas-sas should be using SasSasRsaBaseUrl rather than AdminApiBaseUrl.

in my case, AdminApiBaseUrl = localhost:9000 and SasSasRsaBaseUrl = localhost:9001

for ex, test SSS_11 will verify TLS handshake with AdminApiBaseUrl = localhost:9000, but supposed to verify against SasSasRsaBaseUrl = localhost:9001.

**Comment by pmarks-net** [comment]
Let's see, this is where the values go:

    AdminApiBaseUrl  -> admin_api_base_url   -> SasAdminImpl(arg 0) -> _sas_admin._base_url
    SasSasRsaBaseUrl -> sas_sas_rsa_base_url -> SasImpl(arg 2)      -> _sas_._sas_sas_rsa_base_url

`assertTlsHandshakeFailure` (called from `assertTlsHandshakeFailureOrHttp403`) currently hard-codes `_sas_admin._base_url` as its target.  Do you mean that assertTlsHandshakeFailure* should *always* use `_sas._sas_sas_rsa_base_url`, or that each caller should decide?

**Comment by chandanahs** [comment]
Regarding `assertTlsHandshakeFailureOrHttp403`, this function accepts an argument "is_sas",
If is_sas is True we can pass _sas_._sas_sas_rsa_base_url, else _sas_admin._base_url to `assertTlsHandshakeFailure`.
 i have added this little code to my code base,
```
def assertTlsHandshakeFailureOrHttp403(self, client_cert, client_key, ciphers=None, ssl_method=None, is_sas=False):
    try:
      self.assertTlsHandshakeFailure(client_cert, client_key, ciphers, ssl_method, is_sas=is_sas)

def assertTlsHandshakeFailure(self, client_cert, client_key, ciphers=None, ssl_method=None, is_sas=False):
.
.
    _base_url = self._sas._sas_sas_rsa_base_url if is_sas else self._sas_admin._base_url
    self.assertFalse(
      self.doTlsHandshake(_base_url, client_cert, client_key,
                          ciphers, ssl_method),
      "Handshake succeeded unexpectedly")
```

Regarding `assertTlsHandshakeSucceed` ,
i feel, All SAS-SAS security tests should execute the TLS handshake with `_sas_._sas_sas_rsa_base_url`,
For SCS and SDS, handshake would be with `_sas_admin._base_url`.

test_WINNF_FT_S_SSS_15 : is using `_sas_admin._base_url` for TLS handshake verification, which should be changed to `_sas_._sas_sas_rsa_base_url`,

Pls let me know if my understanding is not correct.

**Comment by pmarks-net** [comment]
I don't know whether your understanding is correct, because you've only shared your conclusions, not the reasoning behind them.

Given that there are several `base_url`s and several call sites, what is the procedure by which we should define the mapping between them?

How should we decide between [`sas_admin`, `sas_sas`, `sas_cbsd`], and between [`rsa`, `ec`, `active`]?  I'm not very familiar with this code, and I can't reasonably alter it without knowing what rules to base it on.

**Comment by redtechnologies** [comment]
I agree, assertTlsHandshakeFailure should never use admin url: either sas_sas either sas_cbsd. There is no point checking admin_url tsl handshake is failing.

@pmarks-net : the url to use depends of the test case that is why is_sas should be used as suggested by @chandanahs. Between RSA/ECC, by default all requests are using RSA except test case that are explicitly testing ECC which are cipher test case. S*S_1 to S*S_5 are cipher test cases. S*S_1 and S*S_2 are RSA cipher and S*S_3, S*S_4 and S*S_5 are testing ECC ciphers.

Paul

**Comment by pmarks-net** [comment]
@chandanahs, does the above pull request do what you were expecting?

**Comment by chandanahs** [comment]
Hi, As long as, admin/sas to cbsd/sas to domain proxy URL are same. It looks fine for me!
