### ISSUE TITLE
REG_2/MES_2 test fails if it is executed after a EPR test

### ISSUE THREAD

**Issue by chandanahs** [Wireless-Innovation-Forum/Spectrum-Access-System#815]
Device f   :   
grep -E "latitude|longitude" testcases/testdata/device_f.json
    "latitude": 38.815291,
    "longitude": -100.253004,
ESC_1: 
grep -E "latitude|longitude" testcases/testdata/esc_sensor_record_0.json
    "latitude": 38.8,
    "longitude": -100.25,

distance from device f to ESC is 1.72 KM, so grant of device f is getting rejected, we may have to change the co-ordinates of device f/ESC device.

**Comment by chandanahs** [comment]
shouldn't this injected test/dummy ESC be removed after EPR testing or in reset baseline state?

As the test/dummy ESC injected, will not be removed post test/ during Reset test Api execution, Heartbeat request in FAD_2 for a cbsd whose coordinates are near to ESC is failing, even thought the ESC addition is suppose to happen in later steps in Daily Activies/CPAS.

`    transmit_expire_times = self.**assertHeartbeatsSuccessful**(cbsd_ids, grant_ids,
                                                            ['GRANTED', 'GRANTED'])   #Execution fails here as ESC introduced in previous test execution is not removed as part of postconditions/ SAS Reset.

    # Notify the SAS UUT about the SAS Test Harness
    certificate_hash = getCertificateFingerprint(config['sasTestHarnessConfig']['serverCert'])
    self._sas_admin.InjectPeerSas({'certificateHash': certificate_hash,
                                   'url': sas_test_harness.getBaseUrl()})

    # Injecting the PAL Records of the PPA into SAS UUT.
    for pal_record in config['palRecords']:
      try:
        self._sas_admin.InjectPalDatabaseRecord(pal_record)
      except Exception:
        logging.error(common_strings.CONFIG_ERROR_SUSPECTED)
        raise

    # Trigger CPAS in the SAS UUT and wait until complete.
    **self.TriggerDailyActivitiesImmediatelyAndWaitUntilComplete()**   #ESC should have been added in this step

    # Send the Heartbeat request again for the G2 and G4 to SAS UUT
    request = {
        'heartbeatRequest': [
            {
                'cbsdId': cbsd_ids[0],
                'grantId': grant_ids[0],
                'operationState': 'GRANTED'
            },
            {
                'cbsdId': cbsd_ids[1],
                'grantId': grant_ids[1],
                'operationState': 'GRANTED'
            }
        ]}
    response = self._sas.Heartbeat(request)['heartbeatResponse']

    # Check the length of request and response match.
    self.assertEqual(len(request['heartbeatRequest']), len(response))

    # Check grant response, must be response code 0.
    for resp in response:
        self.assertTrue(resp['response']['responseCode'] in **(103, 500)**)  # HBT request should fail here.
`

**Comment by kate-harrison** [comment]
The Reset() function is defined to remove all injected data, including ESC sensors, which I think should address your concerns. If not, can you please describe what you think the right solution is?

**Comment by chandanahs** [comment]
yes Kate, But Reset currently dont include removing of injected ESC.

Reset includes only below as per WINNF-TS-0061-V1.3.0 document:

5.4	Baseline State of the SAS UUT
 Unless explicitly stated otherwise as part of the test procedure, the SAS UUT will be reset to the Baseline State at the beginning of every test case. The Reset functionality causes the SAS UUT to delete at least the following data:
•	Information about peer SASs (i.e. the number of peer SASs in the Baseline State is zero)
•	FCC ID whitelist
•	User ID whitelist
•	Blacklist data
•	CBSD data Record, (including Registration and Grant data)
•	Pre-loaded REG-Conditional Registration data
•	FSS data
•	GWPZ data
•	PAL database records
•	PPAs
•	CPI information
•	All data obtained from other SASs (including SAS Test Harnesses)
•	Exclusion zones which cannot be monitored by an ESC
•	CBSD ID

Yes, if the injected test ESC is removed during Reset, this problem will be solved.

**Comment by kate-harrison** [comment]
Thanks!
