### ISSUE TITLE
Error in eHata when calculating effective terminal heights for paths between 3.0 km and 15.0 km

### ISSUE THREAD

**Issue by wkozmaNTIA** [Wireless-Innovation-Forum/Spectrum-Access-System#816]
We discovered the following issue in the eHata model.

Let _WinnForum_Extensions = FALSE.  This means that the WF eHata code should match (compute the same results as) the ITS eHata code (with the exceptions of the issues filed in the ITS code base last week that are not yet reviewed by ITS)

WF computes the effective terminal heights as follows:
[ExtendedHata.cpp:Line 100]
interValues->h_m_eff__meter = h_m__meter + pfl[2] - interValues->h_avg__meter[0];
interValues->h_b_eff__meter = h_b__meter + pfl[np + 2] - interValues->h_avg__meter[1];

For paths 3.0 km <= d__km <= 15.0 km, the average terminal ground height is computed as:
[PreprocessTerrainPath.cpp:Line 79 & 86]
interValues->h_avg__meter[0] = sum / (i_end - i_start + 1) * (d__km - 3.0) / 12.0;
interValues->h_avg__meter[1] = sum / (i_end - i_start + 1) * (d__km - 3.0) / 12.0;
with 'sum' being the summation of all points in the pfl.

Algebraic substitution for the terminal effective height calculations results in:
interValues->h_m_eff__meter = h_m__meter + pfl[2] - sum / (i_end - i_start + 1) * (d__km - 3.0) / 12.0;
interValues->h_b_eff__meter = h_b__meter + pfl[np + 2] - sum / (i_end - i_start + 1) * (d__km - 3.0) / 12.0;

In the ITS eHata code base, the effective terminal heights are computed as:
[PreprocessTerrainPath.cpp:Line 68]
interValues->h_m_eff__meter = h_m__meter + interValues->h_avg__meter[0];
interValues->h_b_eff__meter = h_b__meter + interValues->h_avg__meter[1];

with average terminal terrain heights calculated as:
[PreprocessTerrainPath.cpp:Line 59 & 66]
interValues->h_avg__meter[0] = (d__km - 3.0) / 12.0 * (pfl[2] - sum / (i_end - i_start + 1));
interValues->h_avg__meter[1] = (d__km - 3.0) / 12.0 * (pfl[np + 2] - sum / (i_end - i_start + 1));

Algebraic substitution for the terminal effective height calculations results in:
interValues->h_m_eff__meter = h_m__meter + (d__km - 3.0) / 12.0 * (pfl[2] - sum / (i_end - i_start + 1));
interValues->h_b_eff__meter = h_b__meter + (d__km - 3.0) / 12.0 * (pfl[np + 2] - sum / (i_end - i_start + 1));

It can visibly seen that these two methods are different, specifically, the leading term (d__km - 3.0) / 12.0 on pfl[] was dropped in the WF eHata code.

**Comment by sbdt-google** [comment]
Winnforum does not use the mode  "_WinnForum_Extensions = FALSE".
This code you are referring to is the exact code that was present in the NTIA EHata original version prior
to December 2017. As you point out here, that code has a big issue and this is why we fixed in the
Winnforum_extension version.

We kept the old code under the flag "Winnforum_Extensions=False" just for reference and to be able to
run the original unit tests.  I remember that you fixed it in the NTIA version but with a slightly different method than the one used by Winnforum.
 
I guess that the confusion comes from the fact that we have not reported those changes that you made on your version, since this code is never used in practice.

**Comment by wkozmaNTIA** [comment]
Ahh, I see.  We did make a change based on inputs from Clegg back in Nov 2017 (which you correctly stated were did not reflect back into the Extensions = FALSE code block).  However, it does appear that you implemented the correction the same as ITS under the Extensions = TRUE code block.

Given that this is resolved (and explained/documented in this thread), I'll close out this issue.

**Comment by sbdt-google** [comment]
Please note however that our correction is slightly different of yours.
For example we use 'ceil()' so that the samples to use are strictly in between 3km and 15km. Add possibly
other small difference that I would need to check.

**Comment by sbdt-google** [comment]
BTW I will probably need to report the changes you made at ITS to remove this confusion.

**Comment by wkozmaNTIA** [comment]
Yes, I did see those minor differences.  We can account for those in our testing without too much trouble.  It was more the large differences due to the different equations that caused us to look into the cause more deeply.
