### ISSUE TITLE
util.getRandomLatLongInPolygon returns lat long with 14 digits after decimal, But SAS-CBSD requirement says 6 digits after decimal

### ISSUE THREAD

**Issue by chandanahs** [Wireless-Innovation-Forum/Spectrum-Access-System#822]
getRandomLatLongInPolygon returns lat long with 14 digits after decimal.

SAS-CBSD requirement says "Latitude of the CBSD antenna location in degrees relative to the WGS 84 datum [n.11]. The allowed range is from -90.000000 to +90.000000. Positive values represent latitudes north of the equator; negative values south of the equator. Values are specified using 6 digits to the right of the decimal point."

And FAD_1 test fails as lat/long sent in request (38.77693566715789/-97.20361504249222) are not equal to the registered CBSD coordinates (38.776936/-97.203615)

======================================================================
FAIL: test_WINNF_FT_S_FAD_1_0_default (WINNF_FT_S_FAD_testcase.FullActivityDumpTestcase)
This test verifies that a SAS UUT can successfully respond to a full
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sasuser/code/Regression/Spectrum-Access-System/src/harness/util.py", line 79, in _func
    return func(*a, config_filename=config)
  File "/home/sasuser/code/Regression/Spectrum-Access-System/src/harness/testcases/WINNF_FT_S_FAD_testcase.py", line 478, in test_WINNF_FT_S_FAD_1
    self.assertCbsdRecord(config['registrationRequests'], grants, grant_responses, cbsd_dump_data, config['conditionalRegistrationData'])
  File "/home/sasuser/code/Regression/Spectrum-Access-System/src/harness/testcases/WINNF_FT_S_FAD_testcase.py", line 105, in assertCbsdRecord
    ['installationParam'], cbsd_record[0]['installationParam'])
  File "/home/sasuser/code/Regression/Spectrum-Access-System/src/harness/testcases/WINNF_FT_S_FAD_testcase.py", line 59, in assertEqualToDeviceOrPreloadedConditionalParam
    self.assertEqual(attr_value, record[attr_name])
AssertionError: 38.77693566715789 != 38.776936

Should we change the function to limit the number of digits to 6 post decimal point in getRandomLatLongInPolygon function in util.py?

**Comment by kate-harrison** [comment]
I believe we will want the full precision in other places where that function is used, but it may make sense to limit the precision in the FAD.1 case since we are checking for equality here. Can you please work with Lee Pucker to clear the (small) legal hurdles for contribution and then create a pull request for this?

**Comment by chandanahs** [comment]
I have in the process of getting Contribution permission, I will create a Pull request once i have the permission.

**Comment by chandanahs** [comment]
i did not receive any response from Lee for write permission!
