### ISSUE TITLE
AdminId: sas_admin_id in sas.cfg to be changed to admin_0

### ISSUE THREAD

**Issue by chandanahs** [Wireless-Innovation-Forum/Spectrum-Access-System#825]
as the admin id between PPA records and admin id in sas.cfg are compared in FAD_1, admin id in both testcases/testdata files and sas.cfg should be same.

======================================================================    
FAIL: test_WINNF_FT_S_FAD_1_0_default (WINNF_FT_S_FAD_testcase.FullActivityDumpTestcase)    
This test verifies that a SAS UUT can successfully respond to a full    
----------------------------------------------------------------------    
Traceback (most recent call last):    
  File "/home/sasuser/code/Regression/Spectrum-Access-System/src/harness/util.py", line 79, in _func    
    return func(*a, config_filename=config)    
  File "/home/sasuser/code/Regression/Spectrum-Access-System/src/harness/testcases/WINNF_FT_S_FAD_testcase.py", line 439, in test_WINNF_FT_S_FAD_1    
    **self.assertEqual(ppa_record['id'].split("/")[2], self._sas._sas_admin_id)    
AssertionError: u'admin_0' != 'sas_admin_id'**    

----------------------------------------------------------------------

**Comment by kate-harrison** [comment]
It is expected that the SAS UUT will create a new (correct) ID for the PPA when the PPA is injected into the SAS UUT. This is the reason that we check only parts of the PPA ID but we do not check for exact string equality.
