### ISSUE TITLE
assertContainsRequiredFields breaks in Windows

### ISSUE THREAD

**Issue by nkentNTIA** [Wireless-Innovation-Forum/Spectrum-Access-System#840]
Hey again,

In getting the TH set up on a Windows user's machine, a bug turned up that causes an unhandled exception when checking schema.

Line 270 in `assertContainsRequiredFields` currently reads as follows:

```python
resolver = RefResolver(referrer=schema, base_uri='file://' + schema_dir + '/')
```

The bug can be avoided with this guard:

```python
if os.name == "nt":
    os_base_uri = "file:///"
else:
    os_base_uri = "file:"

resolver = RefResolver(referrer=schema, base_uri=os_base_uri + schema_dir + "/")
```

Thanks again for your help!

**Comment by kate-harrison** [comment]
I'm not sure that we want to officially support a non-Linux OS, but this change is small and harmless enough that I'll defer that discussion/decision until supporting a non-Linux OS is more onerous :)

**Comment by nkentNTIA** [comment]
Haha thanks. Much appreciated. I mostly just wanted him to be able to use one of the reference models and that fix got him there.
