### ISSUE TITLE
Manual/User-guide required

### ISSUE THREAD

**Issue by AvinavKaushik** [Wireless-Innovation-Forum/Spectrum-Access-System#882]
Hi Team,

Can anyone share manual/user-guide for gaining understanding.

**Comment by kate-harrison** [comment]
Please see https://winnf.memberclicks.net/assets/CBRS/WINNF-TS-0061.pdf

**Comment by AvinavKaushik** [comment]
@Kate-harrison Thanks for replying.

Any document regarding code-design?

**Comment by kate-harrison** [comment]
Unfortunately, no: we mostly coordinated via weekly meetings rather than via official documents.
