### ISSUE TITLE
licenseAreaExtent should refer to zone/county/census instead of zone/census_tract/census when using counties in v1.0.27

### ISSUE THREAD

**Issue by diptivete** [Wireless-Innovation-Forum/Spectrum-Access-System#901]
https://github.com/Wireless-Innovation-Forum/Spectrum-Access-System/blob/c223eb8ee77a676cf51a5f77ddd3094bd8982f18/src/harness/util.py#L209`

licenseAreaExtent should be changed to 'zone/county/census' from 'zone/census_tract/census' in makePalRecordsConsistent() under v1.0.27 branch to be used for ITS testing. This is used in InjectPalDatabaseRecord() test api. 

Per SAS admins agreement,
licenseAreaExtent | string | Reference to a record in a geographical database   represented as a SAS-SAS Zone record (See [N.3]) providing the extents of the   license area. (e.g.   “zone/county/census/$YEAR/$FIPS”) | Yes

`   pal_rec['license']['licenseAreaExtent'] = \
      'zone/census_tract/census/{}/{}'.format(pal_census_year, pal_fips_code)`

**Comment by RedaHossino** [comment]
thank you for this remark.
I don't know if that's a blocking issue and need to be fixed on v1.0.27 or it can be done later on v1.0.28, because as mentioned in SAS Admins agreement, the SAS shall use the licenceAreaIdentifier to identify the county.

**Comment by diptivete** [comment]
Thank you for your response. 
Yes, it is blocking issue for us and needs fix on v1.0.27 as 'licenseAreaExtent' is also a mandatory field per spec. It's failing in data validation step during injectPalDatabaseRecord. Affects PCR 1, 2, 4 ,5  as well as WDB.1 testcases.

**Comment by RedaHossino** [comment]
I commited the change on the same PR #900, please feel free to check it.

**Comment by diptivete** [comment]
Thanks .. reviewed and approved.
